import java.io.IOException;

public class Screen extends javax.swing.JFrame {

    
  
    	    public Screen() {
    	        initComponents();
    	    }

    	    /**
    	     * This method is called from within the constructor to initialize the form.
    	     * WARNING: Do NOT modify this code. The content of this method is always
    	     * regenerated by the Form Editor.
    	     */
    	    @SuppressWarnings("unchecked")
    	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    	    private void initComponents() {

    	        jPanel1 = new javax.swing.JPanel();
    	        jLabel1 = new javax.swing.JLabel();
    	        btnrr = new javax.swing.JButton();
    	        btnfcfs = new javax.swing.JButton();
    	        buttonp = new javax.swing.JButton();
    	        jTextField1 = new javax.swing.JTextField();
    	        btnexit = new javax.swing.JButton();
    	        btnrest = new javax.swing.JButton();

    	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    	        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 102)));

    	        jLabel1.setText("Select Scheduling Algorithm");

    	        btnrr.setText("Round Robin");
    	        btnrr.addInputMethodListener(new java.awt.event.InputMethodListener() {
    	            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
    	                btnrrInputMethodTextChanged(evt);
    	            }
    	            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
    	            }
    	        });
    	        btnrr.addActionListener(new java.awt.event.ActionListener() {
    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
    	                btnrrActionPerformed(evt);
    	            }
    	        });

    	        btnfcfs.setText("First Come First Serve");
    	        btnfcfs.addActionListener(new java.awt.event.ActionListener() {
    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
    	                btnfcfsActionPerformed(evt);
    	            }
    	        });

    	        buttonp.setText("Priority");

    	        jTextField1.addActionListener(new java.awt.event.ActionListener() {
    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
    	                jTextField1ActionPerformed(evt);
    	            }
    	        });

    	        btnexit.setForeground(new java.awt.Color(255, 51, 51));
    	        btnexit.setText("Exit");
    	        btnexit.addActionListener(new java.awt.event.ActionListener() {
    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
    	                btnexitActionPerformed(evt);
    	            }
    	        });

    	        btnrest.setText("Reset");
    	        btnrest.addActionListener(new java.awt.event.ActionListener() {
    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
    	                btnrestActionPerformed(evt);
    	            }
    	        });

    	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    	        jPanel1.setLayout(jPanel1Layout);
    	        jPanel1Layout.setHorizontalGroup(
    	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
    	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	                    .addGroup(jPanel1Layout.createSequentialGroup()
    	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	                            .addComponent(btnexit)
    	                            .addGroup(jPanel1Layout.createSequentialGroup()
    	                                .addGap(16, 16, 16)
    	                                .addComponent(btnrr)))
    	                        .addGap(53, 53, 53)
    	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	                            .addComponent(btnfcfs)
    	                            .addComponent(jLabel1))
    	                        .addGap(33, 76, Short.MAX_VALUE)
    	                        .addComponent(buttonp))
    	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
    	                        .addContainerGap()
    	                        .addComponent(btnrest)
    	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    	                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
    	                .addGap(22, 22, 22))
    	        );
    	        jPanel1Layout.setVerticalGroup(
    	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	            .addGroup(jPanel1Layout.createSequentialGroup()
    	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	                    .addGroup(jPanel1Layout.createSequentialGroup()
    	                        .addGap(32, 32, 32)
    	                        .addComponent(jLabel1))
    	                    .addGroup(jPanel1Layout.createSequentialGroup()
    	                        .addContainerGap()
    	                        .addComponent(btnexit)))
    	                .addGap(18, 18, 18)
    	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
    	                    .addComponent(btnfcfs)
    	                    .addComponent(buttonp)
    	                    .addComponent(btnrr))
    	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
    	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
    	                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                    .addComponent(btnrest))
    	                .addContainerGap())
    	        );

    	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    	        getContentPane().setLayout(layout);
    	        layout.setHorizontalGroup(
    	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
    	                .addContainerGap()
    	                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    	                .addContainerGap())
    	        );
    	        layout.setVerticalGroup(
    	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	            .addGroup(layout.createSequentialGroup()
    	                .addContainerGap()
    	                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    	                .addContainerGap())
    	        );

    	        pack();
    	    }// </editor-fold>                        

    	    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	        // TODO add your handling code here:
    	    }                                           

    	    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	        System.exit(0);
    	    }                                      
    	   
    	  
    	    
    	    private void btnfcfsActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	        // TODO add your handling code here:
    	    }                                       

    	    private void btnrrActionPerformed(java.awt.event.ActionEvent evt) {                                      
    	      
    	    }                                     
    	
    	    private void btnrrInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                             
    	        // TODO add your handling code here:
    	    }                                            

    	    private void btnrestActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	        // TODO add your handling code here:
    	    }                                       

    	    /**
    	     * @param args the command line arguments
    	     */
    	    public static void main(String args[]) {
    	        /* Set the Nimbus look and feel */
    	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    	         */
    	        try {
    	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    	                if ("Nimbus".equals(info.getName())) {
    	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
    	                    break;
    	                }
    	            }
    	        } catch (ClassNotFoundException ex) {
    	            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    	        } catch (InstantiationException ex) {
    	            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    	        } catch (IllegalAccessException ex) {
    	            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    	            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    	        }
    	        //</editor-fold>

    	        /* Create and display the form */
    	        java.awt.EventQueue.invokeLater(new Runnable() {
    	            public void run() {
    	                new Screen().setVisible(true);
    	            }
    	        });
    	    }

    	    // Variables declaration - do not modify                     
    	    private javax.swing.JButton btnexit;
    	    private javax.swing.JButton btnfcfs;
    	    private javax.swing.JButton btnrest;
    	    private javax.swing.JButton btnrr;
    	    private javax.swing.JButton buttonp;
    	    private javax.swing.JLabel jLabel1;
    	    private javax.swing.JPanel jPanel1;
    	    private javax.swing.JTextField jTextField1;
    	    // End of variables declaration                   
    	}